version: "3.8"
services:
    server:
        container_name: "sceta-server"
        restart: always
        build:
            dockerfile: ./Dockerfile
            context: .
        command:
            - --config=/server/data.yaml
            - --host=0.0.0.0
            - --port=8001
        volumes:
            - ./data.yaml:/server/data.yaml
            - ./app.py:/server/app.py
            - ./modules:/server/modules
        ports:
            - 8001:8001
    prometheus:
        image: prom/prometheus:latest
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
        ports:
            - 9090:9090
    nginx:
        container_name: sceta-nginx
        image: nginx:alpine
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 80:80
