version: "3.8"
services:
    frontend:
        restart: on-failure
        build:
            dockerfile: ./docker/Dockerfile.dev
            context: ./frontend
        volumes:
            - ./frontend/package.json:/frontend/package.json
            - ./frontend/src:/frontend/src/
            - ./frontend/public:/frontend/public/
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
    server:
        restart: always
        build:
            dockerfile: ./Dockerfile
            context: ./server
        command:
            - --config=/server/data.yaml
            - --port=8001
            - --fixed-stops=/server/fixed_stops.json
            - -vvv
        volumes:
            - ./server/data.yaml:/server/data.yaml:ro
            - ./server/app.py:/server/app.py
            - ./server/modules:/server/modules
            - ./server/fixed_stops.json:/server/fixed_stops.json:ro
        environment:
            - WATCHFILES_FORCE_POLLING=true
    prometheus:
        image: prom/prometheus:latest
        restart: always
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - --config.file=/etc/prometheus/prometheus.yml
    nginx:
        image: nginx:alpine
        volumes:
            - ./nginx.dev.conf:/etc/nginx/nginx.conf
        ports:
            - 3001:80
